apiVersion: apps/v1
kind: Deployment
metadata:
  name: covid-app
  labels:
    app: covid-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: covid-app
  template:
    metadata:
      labels:
        app: covid-app
    spec:
      containers:
        - name: covid-app
          image: covid-app
          env:
            - name: SOME_ENV
              value: $SOME_ENV
          ports:
            - containerPort: 8080
